services:
  - type: web
    name: crm-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5002
      - key: USUARIO_BD
        sync: false
      - key: CONTRASENA_BD
        sync: false
      - key: SERVIDOR_BD
        sync: false
      - key: NOMBRE_BD
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true